# This file is automatically @generated by Poetry 1.5.1 and should not be changed by hand.
package = []

[metadata]
lock-version = "2.0"
python-versions = ">=3.8.0,<3.9"
content-hash = "a577f4577bfd157e62cc369f06956536aa854db6f2e566ddf62da606d6e7f35d"
